{image,package}/python: major refactor
- deduplicate files in package/python
- restore original Debian patches for 3.9..3.11:
  - distutils-install-layout.diff
  - sysconfig-debian-schemes.diff
- backport patches from Debian:
  - shutdown-deadlock.diff
- rework/rename own layout patch:
  - install system-wide packages in /usr/lib/python{pyver}/site-packages/
  - enumerate Debian's Python package folders as last resort (in that order):
    - /usr/local/lib/python{pyver}/dist-packages/
    - /usr/lib/python3/dist-packages/
    - /usr/lib/python{pyver}/dist-packages/
  - minor adjustments
- rework Provides field
- adjust Conflicts/Breaks fields
- simplify versioning for shim packages
- adjust ensurepip to provide pip and setuptools of same version as installed/upgraded while package build
- adjust default pip.conf: disable checking for pip updates
- run build tests in parallel at half of provided parallel job count or available "cpus";
  doesn't affect PGO tests - they're still run sequentially
- separate script to build shim packages
- package build: account CI env variable for "is rebuild required?" trick;
  assume that if CI env variable isn't empty - trick isn't required at all
- image build optimization: use "-apt" variants if applicable;
  use "-apt" variants only if APT_REPO_PREFIX env variable isn't empty

Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>

diff --git a/image/python/Dockerfile b/image/python/Dockerfile
--- a/image/python/Dockerfile
+++ b/image/python/Dockerfile
@@ -11,6 +11,8 @@ ARG PYTHON_MIN_IMAGE
 FROM ${IMAGE_PATH}/${BUILD_IMAGE} as build
 SHELL [ "/bin/sh", "-ec" ]
 
+ARG CI
+
 # these directories should be mounted as RW volumes
 ARG DEB_SRC_BUILD_DIR
 ARG _SRC_DIR
@@ -25,33 +27,18 @@ ARG PYTHON_BASE_VERSION
 ARG DEB_BUILD_OPTIONS
 
 # build context should be set to /package/python/
-COPY /shim/ /tmp/debian/
-
-RUN mkdir -p ${_SRC_DIR} ; \
-    deb-src-export ${_SRC_DIR} /tmp/debian ; \
-    mkdir -p ${_PKG_DIR} ; \
-    set +e ; \
-    # "/ciep.sh env" ensures that container limits are taken in account
-    /ciep.sh env \
-      deb-src-build ${_SRC_DIR}/container-shim-python-*.dsc ${_PKG_DIR} ; \
-    result=$? ; \
-    set -e ; \
-    cleanup ; \
-    echo "# build return code: ${result}" ; \
-    [ "${result}" = 0 ] || exit ${result}
-
-# build context should be set to /package/python/
+COPY /template/ /tmp/debian/
 COPY /${PYTHON_BASE_VERSION}/ /tmp/debian/
 
-RUN if find ${_PKG_DIR}/ -maxdepth 1 -name "container-python-*_${PYTHON_VERSION}-*_*.buildinfo" -type f -printf . -quit 2>/dev/null | grep -Fq . ; then \
-      cleanup ; \
-      exit 0 ; \
+RUN if [ -z "${CI}" ] ; then \
+      if find ${_PKG_DIR}/ -maxdepth 1 -name "container-python-*_${PYTHON_VERSION}-*_*.buildinfo" -type f -printf . -quit 2>/dev/null | grep -Fq . ; then \
+        cleanup ; \
+        exit 0 ; \
+      fi ; \
     fi ; \
     build_start=$(date -R) ; \
     apt-update ; \
-    mkdir -p ${_SRC_DIR} ; \
     deb-src-export ${_SRC_DIR} /tmp/debian ; \
-    mkdir -p ${_PKG_DIR} ; \
     set +e ; \
     # "/ciep.sh env" ensures that container limits are taken in account
     /ciep.sh env \
@@ -67,13 +54,44 @@ RUN if find ${_PKG_DIR}/ -maxdepth 1 -name "container-python-*_${PYTHON_VERSION}
 
 # ---
 
+FROM ${IMAGE_PATH}/${BUILD_IMAGE} as build-shim
+SHELL [ "/bin/sh", "-ec" ]
+
+ARG CI
+
+# these directories should be mounted as RW volumes
+ARG DEB_SRC_BUILD_DIR
+ARG _SRC_DIR
+ARG _PKG_DIR
+
+ARG DISTRO
+ARG SUITE
+
+ARG PYTHON_VERSION
+ARG PYTHON_BASE_VERSION
+
+# build context should be set to /package/python/
+COPY /shim/ /tmp/debian/
+
+RUN deb-src-export ${_SRC_DIR} /tmp/debian ; \
+    set +e ; \
+    # "/ciep.sh env" ensures that container limits are taken in account
+    /ciep.sh env \
+      deb-src-build ${_SRC_DIR}/container-shim-python-*.dsc ${_PKG_DIR} ; \
+    result=$? ; \
+    set -e ; \
+    cleanup ; \
+    echo "# build return code: ${result}" ; \
+    [ "${result}" = 0 ] || exit ${result}
+
+# ---
+
 FROM ${IMAGE_PATH}/${BASE_IMAGE} as minimal
 SHELL [ "/bin/sh", "-ec" ]
 
 COPY --from=packages [ \
   "container-python-${PYTHON_BASE_VERSION}_*.deb", \
   "container-shim-python-${PYTHON_BASE_VERSION}_*.deb", \
-  "container-shim-unqual-python-${PYTHON_BASE_VERSION}_*.deb", \
   "/tmp/" ]
 
 RUN dpkg -i /tmp/*.deb || apt-install --fix-broken ; \
@@ -95,9 +113,7 @@ COPY --from=packages [ \
   "container-python-${PYTHON_BASE_VERSION}-dev_*.deb", \
   "container-python-${PYTHON_BASE_VERSION}-full_*.deb", \
   "container-shim-python-${PYTHON_BASE_VERSION}-dev_*.deb", \
-  "container-shim-unqual-python-${PYTHON_BASE_VERSION}-dev_*.deb", \
   "container-shim-python-${PYTHON_BASE_VERSION}-full_*.deb", \
-  "container-shim-unqual-python-${PYTHON_BASE_VERSION}-full_*.deb", \
   "/tmp/" ]
 
 RUN dpkg -i /tmp/*.deb || apt-install --fix-broken ; \
