{image,package}/golang: split shim packages
Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>

diff --git a/image/golang/Dockerfile b/image/golang/Dockerfile
--- a/image/golang/Dockerfile
+++ b/image/golang/Dockerfile
@@ -29,9 +29,25 @@ ARG GOSUMDB
 ARG GOPRIVATE
 
 # build context should be set to /package/golang/
+COPY /shim/ /tmp/debian/
+
+RUN mkdir -p ${_SRC_DIR} ; \
+    deb-src-export ${_SRC_DIR} /tmp/debian ; \
+    mkdir -p ${_PKG_DIR} ; \
+    set +e ; \
+    # "/ciep.sh env" ensures that container limits are taken in account
+    /ciep.sh env \
+      deb-src-build ${_SRC_DIR}/container-shim-golang-*.dsc ${_PKG_DIR} ; \
+    result=$? ; \
+    set -e ; \
+    cleanup ; \
+    echo "# build return code: ${result}" ; \
+    [ "${result}" = 0 ] || exit ${result}
+
+# build context should be set to /package/golang/
 COPY /${GOLANG_BASE_VERSION}/ /tmp/debian/
 
-RUN if find ${_PKG_DIR}/ -maxdepth 1 -name "*_${GOLANG_VERSION}-*_*.buildinfo" -type f -printf . -quit 2>/dev/null | grep -Fq . ; then \
+RUN if find ${_PKG_DIR}/ -maxdepth 1 -name "container-golang-*_${GOLANG_VERSION}-*_*.buildinfo" -type f -printf . -quit 2>/dev/null | grep -Fq . ; then \
       exit 0 ; \
     fi ; \
     build_start=$(date -R) ; \
@@ -42,7 +58,7 @@ RUN if find ${_PKG_DIR}/ -maxdepth 1 -name "*_${GOLANG_VERSION}-*_*.buildinfo" -
     set +e ; \
     # "/ciep.sh env" ensures that container limits are taken in account
     /ciep.sh env \
-      deb-src-build ${_SRC_DIR}/*.dsc ${_PKG_DIR} ; \
+      deb-src-build ${_SRC_DIR}/container-golang-*.dsc ${_PKG_DIR} ; \
     result=$? ; \
     set -e ; \
     build_finish=$(date -R) ; \
@@ -60,6 +76,8 @@ SHELL [ "/bin/sh", "-ec" ]
 COPY --from=packages [ \
   "container-golang-${GOLANG_BASE_VERSION}_*.deb", \
   "container-golang-${GOLANG_BASE_VERSION}-src_*.deb", \
+  "container-shim-golang-${GOLANG_BASE_VERSION}_*.deb", \
+  "container-shim-golang-${GOLANG_BASE_VERSION}-src_*.deb", \
   "/tmp/" ]
 
 RUN dpkg -i /tmp/*.deb || apt-install --fix-broken ; \
@@ -85,7 +103,6 @@ ARG GOLANG_BASE_VERSION
 
 COPY --from=packages [ \
   "container-golang-${GOLANG_BASE_VERSION}-full_*.deb", \
-  "container-golang-${GOLANG_BASE_VERSION}-misc_*.deb", \
   "/tmp/" ]
 
 RUN dpkg -i /tmp/*.deb || apt-install --fix-broken ; \
