image/{golang,python}: split/refactor
- build packages then images
- cleanup dockerfiles

Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>

diff --git a/image/golang/Dockerfile b/image/golang/Dockerfile
--- a/image/golang/Dockerfile
+++ b/image/golang/Dockerfile
@@ -15,7 +15,6 @@ SHELL [ "/bin/sh", "-ec" ]
 # these directories should be mounted as RW volumes
 ARG DEB_SRC_BUILD_DIR
 ARG _SRC_DIR
-# ARG _PKG_DIR=/usr/local/lib
 ARG _PKG_DIR
 
 ARG DISTRO
@@ -26,49 +25,43 @@ ARG GOPROXY
 ARG GOSUMDB
 ARG GOPRIVATE
 
+# build context should be set to /package/golang/
 COPY /${GOLANG_BASE_VERSION}/ /tmp/debian/
 
-ARG DEB_SRC_BUILD_PURGE
 ARG DEB_BUILD_OPTIONS
 
-RUN if ! find ${_PKG_DIR}/ -maxdepth 1 -name "*_${GOLANG_VERSION}-*_*.buildinfo" -type f -printf . -quit 2>/dev/null | grep -Fq . ; then \
-        build_start=$(date -R) ; \
-        apt-update ; \
-        mkdir -p ${_SRC_DIR} ; \
-        deb-src-export ${_SRC_DIR} /tmp/debian ; \
-        mkdir -p ${_PKG_DIR} ; \
-        set +e ; \
-        # "/ciep.sh env" ensures that container limits are taken in account
-        /ciep.sh env \
-          deb-src-build ${_SRC_DIR}/*.dsc ${_PKG_DIR} ; \
-        result=$? ; \
-        set -e ; \
-        build_finish=$(date -R) ; \
-        cleanup ; \
-        echo "# build started at:  ${build_start}" ; \
-        echo "# build finished at: ${build_finish}" ; \
-        echo "# build return code: ${result}" ; \
-        [ "${result}" = 0 ] || exit ${result} ; \
+RUN if find ${_PKG_DIR}/ -maxdepth 1 -name "*_${GOLANG_VERSION}-*_*.buildinfo" -type f -printf . -quit 2>/dev/null | grep -Fq . ; then \
+      exit 0 ; \
     fi ; \
-    # linkage with final layer
-    cp ${_PKG_DIR}/*_${GOLANG_VERSION}-*_*.buildinfo /tmp/
+    build_start=$(date -R) ; \
+    apt-update ; \
+    mkdir -p ${_SRC_DIR} ; \
+    deb-src-export ${_SRC_DIR} /tmp/debian ; \
+    mkdir -p ${_PKG_DIR} ; \
+    set +e ; \
+    # "/ciep.sh env" ensures that container limits are taken in account
+    /ciep.sh env \
+      deb-src-build ${_SRC_DIR}/*.dsc ${_PKG_DIR} ; \
+    result=$? ; \
+    set -e ; \
+    build_finish=$(date -R) ; \
+    cleanup ; \
+    echo "# build started at:  ${build_start}" ; \
+    echo "# build finished at: ${build_finish}" ; \
+    echo "# build return code: ${result}" ; \
+    [ "${result}" = 0 ] || exit ${result}
 
 # ---
 
 FROM ${IMAGE_REGISTRY}/${IMAGE_DIRECTORY}/${BASE_IMAGE} as minimal
 SHELL [ "/bin/sh", "-ec" ]
 
-# linkage with build layer
-COPY --from=build  /tmp/*.buildinfo  /tmp/
+COPY --from=packages [ \
+  "container-golang-${GOLANG_BASE_VERSION}_*.deb", \
+  "container-golang-${GOLANG_BASE_VERSION}-src_*.deb", \
+  "/tmp/" ]
 
-# this directory should be mounted as volume
-# ARG _PKG_DIR=/usr/local/lib
-
-RUN arch=$(dpkg --print-architecture) ; \
-    gobasever=$(echo "${GOLANG_VERSION}" | cut -d. -f1-2) ; \
-    find /usr/local/lib/ -regextype egrep -regex ".+/container-golang-${gobasever}(|-src)_.+_(all|${arch})\\.deb\$" -type f \
-      -exec dpkg -i '{}' '+' \
-    || apt-install --fix-broken ; \
+RUN dpkg -i /tmp/*.deb || apt-install --fix-broken ; \
     cleanup ; \
     # smoke/qa
     set -xv ; \
@@ -81,14 +74,12 @@ CMD [ "go" ]
 FROM ${IMAGE_REGISTRY}/${IMAGE_DIRECTORY}/${GOLANG_MIN_IMAGE} as regular
 SHELL [ "/bin/sh", "-ec" ]
 
-# this directory should be mounted as volume
-# ARG _PKG_DIR=/usr/local/lib
+COPY --from=packages [ \
+  "container-golang-${GOLANG_BASE_VERSION}-full_*.deb", \
+  "container-golang-${GOLANG_BASE_VERSION}-misc_*.deb", \
+  "/tmp/" ]
 
-RUN arch=$(dpkg --print-architecture) ; \
-    gobasever=$(echo "${GOLANG_VERSION}" | cut -d. -f1-2) ; \
-    find /usr/local/lib/ -regextype egrep -regex ".+/container-golang-${gobasever}(-full|-misc)_.+_(all|${arch})\\.deb\$" -type f \
-      -exec dpkg -i '{}' '+' \
-    || apt-install --fix-broken ; \
+RUN dpkg -i /tmp/*.deb || apt-install --fix-broken ; \
     cleanup ; \
     # smoke/qa
     set -xv ; \
@@ -99,8 +90,7 @@ RUN arch=$(dpkg --print-architecture) ; \
 FROM ${IMAGE_REGISTRY}/${IMAGE_DIRECTORY}/${BASE_IMAGE} as minimal-apt
 SHELL [ "/bin/sh", "-ec" ]
 
-RUN gobasever=$(echo "${GOLANG_VERSION}" | cut -d. -f1-2) ; \
-    apt-install container-golang-${gobasever} ; \
+RUN apt-install container-golang-${GOLANG_BASE_VERSION} ; \
     cleanup ; \
     # smoke/qa
     set -xv ; \
@@ -113,8 +103,7 @@ CMD [ "go" ]
 FROM ${IMAGE_REGISTRY}/${IMAGE_DIRECTORY}/${GOLANG_MIN_IMAGE} as regular-apt
 SHELL [ "/bin/sh", "-ec" ]
 
-RUN gobasever=$(echo "${GOLANG_VERSION}" | cut -d. -f1-2) ; \
-    apt-install container-golang-${gobasever}-full ; \
+RUN apt-install container-golang-${GOLANG_BASE_VERSION}-full ; \
     cleanup ; \
     # smoke/qa
     set -xv ; \
diff --git a/image/python/Dockerfile b/image/python/Dockerfile
--- a/image/python/Dockerfile
+++ b/image/python/Dockerfile
@@ -15,63 +15,48 @@ SHELL [ "/bin/sh", "-ec" ]
 # these directories should be mounted as RW volumes
 ARG DEB_SRC_BUILD_DIR
 ARG _SRC_DIR
-# ARG _PKG_DIR=/usr/local/lib
 ARG _PKG_DIR
 
 ARG DISTRO
 ARG SUITE
 ARG PYTHON_BASE_VERSION
 
+# build context should be set to /package/python/
 COPY /${PYTHON_BASE_VERSION}/ /tmp/debian/
 
-ARG DEB_SRC_BUILD_PURGE
 ARG DEB_BUILD_OPTIONS
 
-RUN if ! find ${_PKG_DIR}/ -maxdepth 1 -name "*_${PYTHON_VERSION}-*_*.buildinfo" -type f -printf . -quit 2>/dev/null | grep -Fq . ; then \
-        build_start=$(date -R) ; \
-        apt-update ; \
-        mkdir -p ${_SRC_DIR} ; \
-        deb-src-export ${_SRC_DIR} /tmp/debian ; \
-        mkdir -p ${_PKG_DIR} ; \
-        set +e ; \
-        # "/ciep.sh env" ensures that container limits are taken in account
-        /ciep.sh env \
-          deb-src-build ${_SRC_DIR}/*.dsc ${_PKG_DIR} ; \
-        result=$? ; \
-        set -e ; \
-        build_finish=$(date -R) ; \
-        cleanup ; \
-        echo "# build started at:  ${build_start}" ; \
-        echo "# build finished at: ${build_finish}" ; \
-        echo "# build return code: ${result}" ; \
-        [ "${result}" = 0 ] || exit ${result} ; \
+RUN if find ${_PKG_DIR}/ -maxdepth 1 -name "*_${PYTHON_VERSION}-*_*.buildinfo" -type f -printf . -quit 2>/dev/null | grep -Fq . ; then \
+      exit 0 ; \
     fi ; \
-    # linkage with final layer
-    cp ${_PKG_DIR}/*_${PYTHON_VERSION}-*_*.buildinfo /tmp/
+    build_start=$(date -R) ; \
+    apt-update ; \
+    mkdir -p ${_SRC_DIR} ; \
+    deb-src-export ${_SRC_DIR} /tmp/debian ; \
+    mkdir -p ${_PKG_DIR} ; \
+    set +e ; \
+    # "/ciep.sh env" ensures that container limits are taken in account
+    /ciep.sh env \
+      deb-src-build ${_SRC_DIR}/*.dsc ${_PKG_DIR} ; \
+    result=$? ; \
+    set -e ; \
+    build_finish=$(date -R) ; \
+    cleanup ; \
+    echo "# build started at:  ${build_start}" ; \
+    echo "# build finished at: ${build_finish}" ; \
+    echo "# build return code: ${result}" ; \
+    [ "${result}" = 0 ] || exit ${result}
 
 # ---
 
 FROM ${IMAGE_REGISTRY}/${IMAGE_DIRECTORY}/${BASE_IMAGE} as minimal
 SHELL [ "/bin/sh", "-ec" ]
 
-# linkage with build layer
-COPY --from=build  /tmp/*.buildinfo  /tmp/
+COPY --from=packages [ \
+  "container-python-${PYTHON_BASE_VERSION}_*.deb", \
+  "/tmp/" ]
 
-# this directory should be mounted as volume
-# ARG _PKG_DIR=/usr/local/lib
-
-RUN arch=$(dpkg --print-architecture) ; \
-    pybasever=$(echo "${PYTHON_VERSION}" | cut -d. -f1-2) ; \
-    find /usr/local/lib/ -regextype egrep -regex ".+/container-python-${pybasever}_.+_(all|${arch})\\.deb\$" -type f \
-      -exec dpkg -i '{}' '+' \
-    || apt-install --fix-broken ; \
-    # HACK: enforce system CA bundle usage in "requests"/"certifi"
-#   find /usr/lib/python${pybasever}/ -name cacert.pem -type f \
-#   | while read -r f ; do \
-#       dpkg-divert --divert "$f.local" --rename "$f" ; \
-#       rm -f "$f" ; \
-#       ln -vs ${REQUESTS_CA_BUNDLE} "$f" ; \
-#   done ; \
+RUN dpkg -i /tmp/*.deb || apt-install --fix-broken ; \
     cleanup ; \
     # smoke/qa
     set -xv ; \
@@ -84,16 +69,14 @@ CMD [ "python3" ]
 FROM ${IMAGE_REGISTRY}/${IMAGE_DIRECTORY}/${PYTHON_MIN_IMAGE} as regular
 SHELL [ "/bin/sh", "-ec" ]
 
-# this directory should be mounted as volume
-# ARG _PKG_DIR=/usr/local/lib
+COPY --from=packages [ \
+  "container-python-${PYTHON_BASE_VERSION}-dev_*.deb", \
+  "container-python-${PYTHON_BASE_VERSION}-full_*.deb", \
+  "/tmp/" ]
 
-RUN arch=$(dpkg --print-architecture) ; \
-    pybasever=$(echo "${PYTHON_VERSION}" | cut -d. -f1-2) ; \
-    find /usr/local/lib/ -regextype egrep -regex ".+/container-python-${pybasever}(-dev|-full)_.+_(all|${arch})\\.deb\$" -type f \
-      -exec dpkg -i '{}' '+' \
-    || apt-install --fix-broken ; \
+RUN dpkg -i /tmp/*.deb || apt-install --fix-broken ; \
     # HACK: enforce system CA bundle usage in "requests"/"certifi"
-#   find /usr/lib/python${pybasever}/ -name cacert.pem -type f \
+#   find /usr/lib/python${PYTHON_BASE_VERSION}/ -name cacert.pem -type f \
 #   | while read -r f ; do \
 #       dpkg-divert --divert "$f.local" --rename "$f" ; \
 #       rm -f "$f" ; \
@@ -110,15 +93,7 @@ RUN arch=$(dpkg --print-architecture) ; \
 FROM ${IMAGE_REGISTRY}/${IMAGE_DIRECTORY}/${BASE_IMAGE} as minimal-apt
 SHELL [ "/bin/sh", "-ec" ]
 
-RUN pybasever=$(echo "${PYTHON_VERSION}" | cut -d. -f1-2) ; \
-    apt-install container-python-${pybasever} ; \
-    # HACK: enforce system CA bundle usage in "requests"/"certifi"
-#   find /usr/lib/python${pybasever}/ -name cacert.pem -type f \
-#   | while read -r f ; do \
-#       dpkg-divert --divert "$f.local" --rename "$f" ; \
-#       rm -f "$f" ; \
-#       ln -vs ${REQUESTS_CA_BUNDLE} "$f" ; \
-#   done ; \
+RUN apt-install container-python-${PYTHON_BASE_VERSION} ; \
     cleanup ; \
     # smoke/qa
     set -xv ; \
@@ -131,10 +106,9 @@ CMD [ "python3" ]
 FROM ${IMAGE_REGISTRY}/${IMAGE_DIRECTORY}/${PYTHON_MIN_IMAGE} as regular-apt
 SHELL [ "/bin/sh", "-ec" ]
 
-RUN pybasever=$(echo "${PYTHON_VERSION}" | cut -d. -f1-2) ; \
-    apt-install container-python-${pybasever}-full ; \
+RUN apt-install container-python-${PYTHON_BASE_VERSION}-full ; \
     # HACK: enforce system CA bundle usage in "requests"/"certifi"
-#   find /usr/lib/python${pybasever}/ -name cacert.pem -type f \
+#   find /usr/lib/python${PYTHON_BASE_VERSION}/ -name cacert.pem -type f \
 #   | while read -r f ; do \
 #       dpkg-divert --divert "$f.local" --rename "$f" ; \
 #       rm -f "$f" ; \
