treewide: adjust Dockerfiles and scripts
Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>

diff --git a/image/golang/Dockerfile b/image/golang/Dockerfile
--- a/image/golang/Dockerfile
+++ b/image/golang/Dockerfile
@@ -2,14 +2,84 @@ ARG IMAGE_PATH=docker.io/rockdrilla
 ARG DISTRO=debian
 ARG SUITE=stable
 
+ARG GOLANG_VERSION
+
+ARG BUILD_HELPER_IMAGE=${DISTRO}-buildd-helper:${SUITE}
 ARG BUILD_IMAGE=${DISTRO}-buildd:${SUITE}
 ARG BASE_IMAGE=${DISTRO}-min:${SUITE}
-ARG GOLANG_MIN_IMAGE
+ARG GOLANG_MIN_IMAGE=golang-min:${GOLANG_VERSION}-${SUITE}
 
 # ---
 
-FROM ${IMAGE_PATH}/${BUILD_IMAGE} as build
+FROM ${IMAGE_PATH}/${BUILD_HELPER_IMAGE} as build-shim
 SHELL [ "/bin/sh", "-ec" ]
+
+# these directories should be mounted as RW volumes
+ARG DEB_SRC_BUILD_DIR
+ARG _SRC_DIR
+ARG _PKG_DIR
+
+ARG DISTRO
+ARG SUITE
+
+ARG GOLANG_VERSION
+ARG GOLANG_BASE_VERSION
+
+COPY /package/.template/    /tmp/debian/
+COPY /package/golang/shim/  /tmp/debian/
+
+# "/ciep.env" ensures that container limits and env are taken in account
+RUN set -a ; eval $(/ciep.env) ; set +a ; \
+    build_start=$(date -R) ; \
+    apt-update ; \
+    deb-src-export ${_SRC_DIR} /tmp/debian ; \
+    set +e ; \
+    deb-src-build ${_SRC_DIR}/container-shim-golang-*.dsc ${_PKG_DIR} ; \
+    result=$? ; \
+    set -e ; \
+    build_finish=$(date -R) ; \
+    cleanup ; \
+    echo "# build started at:  ${build_start}" ; \
+    echo "# build finished at: ${build_finish}" ; \
+    echo "# build return code: ${result}" ; \
+    [ "${result}" = 0 ] || exit ${result}
+
+# ---
+
+FROM ${IMAGE_PATH}/${BUILD_HELPER_IMAGE} as build-dsc
+SHELL [ "/bin/sh", "-ec" ]
+
+# this directory should be mounted as RW volume
+ARG _SRC_DIR
+
+ARG DISTRO
+ARG SUITE
+
+ARG GOLANG_VERSION
+ARG GOLANG_BASE_VERSION
+
+ARG DEB_BUILD_OPTIONS
+ARG DEB_BUILD_PROFILES
+
+COPY /package/.template/                      /tmp/debian/
+COPY /package/golang/template/                /tmp/debian/
+COPY /package/golang/${GOLANG_BASE_VERSION}/  /tmp/debian/
+
+# "/ciep.env" ensures that container limits and env are taken in account
+RUN set -a ; eval $(/ciep.env) ; set +a ; \
+    apt-update ; \
+    deb-src-export ${_SRC_DIR} /tmp/debian ; \
+    cleanup ; \
+    # linkage with "build-pkg" layer
+    touch /tmp/dsc
+
+# ---
+
+FROM ${IMAGE_PATH}/${BUILD_IMAGE} as build-pkg
+SHELL [ "/bin/sh", "-ec" ]
+
+# linkage with "build-dsc" layer
+COPY --from=build-dsc /tmp/dsc /tmp/
 
 ARG CI
 
@@ -26,27 +96,27 @@ ARG GOLANG_BASE_VERSION
 
 ARG DEB_BUILD_OPTIONS
 
+# these variables will be hardcoded in packages (!)
 ARG GOPROXY
 ARG GOSUMDB
 ARG GOPRIVATE
 
-COPY /package/.template/                      /tmp/debian/
-COPY /package/golang/template/                /tmp/debian/
-COPY /package/golang/${GOLANG_BASE_VERSION}/  /tmp/debian/
+# CI/manual execution handler
+ENV BUILDINFO_MASK="container-golang-${GOLANG_BASE_VERSION}_${GOLANG_VERSION}-*_*.buildinfo"
+RUN [ -z "${CI}" ] || exit 0; \
+    if find ${_PKG_DIR}/ -maxdepth 1 -name "${BUILDINFO_MASK}" -type f -printf . -quit 2>/dev/null | grep -Fq . ; then \
+      # implicitly deletes /tmp/dsc
+      cleanup ; \
+      exit 0 ; \
+    fi
 
-RUN if [ -z "${CI}" ] ; then \
-      if find ${_PKG_DIR}/ -maxdepth 1 -name "container-golang-${GOLANG_BASE_VERSION}_${GOLANG_VERSION}-*_*.buildinfo" -type f -printf . -quit 2>/dev/null | grep -Fq . ; then \
-        cleanup ; \
-        exit 0 ; \
-      fi ; \
-    fi ; \
-    build_start=$(date -R) ; \
-    apt-update ; \
-    deb-src-export ${_SRC_DIR} /tmp/debian ; \
-    set +e ; \
+RUN [ -e /tmp/dsc ] || exit 0 ; \
     # "/ciep.env" ensures that container limits are taken in account
-    /ciep.env \
-      deb-src-build ${_SRC_DIR}/container-golang-${GOLANG_BASE_VERSION}_${GOLANG_VERSION}-*.dsc ${_PKG_DIR} ; \
+    set -a ; eval $(/ciep.env) ; set +a ; \
+    apt-update ; \
+    build_start=$(date -R) ; \
+    set +e ; \
+    deb-src-build ${_SRC_DIR}/container-golang-${GOLANG_BASE_VERSION}_${GOLANG_VERSION}-*.dsc ${_PKG_DIR} ; \
     result=$? ; \
     set -e ; \
     build_finish=$(date -R) ; \
@@ -58,39 +128,30 @@ RUN if [ -z "${CI}" ] ; then \
 
 # ---
 
-FROM ${IMAGE_PATH}/${BUILD_IMAGE} as build-shim
+FROM ${IMAGE_PATH}/${BASE_IMAGE} as go-layout
 SHELL [ "/bin/sh", "-ec" ]
 
-ARG CI
+ENV GOPATH=/go \
+    GOTMPROOT=/go.tmp \
+    CGO_ENABLED=0
 
-# these directories should be mounted as RW volumes
-ARG DEB_SRC_BUILD_DIR
-ARG _SRC_DIR
-ARG _PKG_DIR
+ENV PATH="${GOPATH}/bin:${PATH}" \
+    GOTMPDIR="${GOTMPROOT}/tmp" \
+    GOCACHE="${GOTMPROOT}/build-cache" \
+    GOMODCACHE="${GOTMPROOT}/mod-cache"
 
-ARG DISTRO
-ARG SUITE
+RUN mkdir -p "${GOPATH}" "${GOPATH}/bin" "${GOPATH}/src" "${GOTMPROOT}" ; \
+    chmod -R 01777 "${GOPATH}" "${GOTMPROOT}"
 
-ARG GOLANG_VERSION
-ARG GOLANG_BASE_VERSION
+WORKDIR "${GOPATH}"
 
-COPY /package/.template/    /tmp/debian/
-COPY /package/golang/shim/  /tmp/debian/
+VOLUME [ "${GOTMPROOT}" ]
 
-RUN deb-src-export ${_SRC_DIR} /tmp/debian ; \
-    set +e ; \
-    # "/ciep.env" ensures that container limits are taken in account
-    /ciep.env \
-      deb-src-build ${_SRC_DIR}/container-shim-golang-*.dsc ${_PKG_DIR} ; \
-    result=$? ; \
-    set -e ; \
-    cleanup ; \
-    echo "# build return code: ${result}" ; \
-    [ "${result}" = 0 ] || exit ${result}
+CMD [ "go" ]
 
 # ---
 
-FROM ${IMAGE_PATH}/${BASE_IMAGE} as minimal
+FROM go-layout as minimal
 SHELL [ "/bin/sh", "-ec" ]
 
 COPY --from=packages [ \
@@ -100,19 +161,11 @@ COPY --from=packages [ \
   "container-shim-golang-${GOLANG_BASE_VERSION}-src_*.deb", \
   "/tmp/" ]
 
-RUN dpkg -i /tmp/*.deb || apt-install --fix-broken ; \
+RUN apt-install /tmp/*.deb ; \
     cleanup ; \
-    install -d -m 0777 /go /go/bin /go/src ; \
     # smoke/qa
     set -xv ; \
     go version
-
-WORKDIR /go
-
-ENV PATH="/go/bin:${PATH}" \
-    GOPATH=/go
-
-CMD [ "go" ]
 
 # ---
 
@@ -123,7 +176,9 @@ COPY --from=packages [ \
   "container-golang-${GOLANG_BASE_VERSION}-full_${GOLANG_VERSION}-*.deb", \
   "/tmp/" ]
 
-RUN dpkg -i /tmp/*.deb || apt-install --fix-broken ; \
+ENV CGO_ENABLED=1
+
+RUN apt-install /tmp/*.deb ; \
     cleanup ; \
     # smoke/qa
     set -xv ; \
@@ -131,27 +186,21 @@ RUN dpkg -i /tmp/*.deb || apt-install --fix-broken ; \
 
 # ---
 
-FROM ${IMAGE_PATH}/${BASE_IMAGE} as minimal-apt
+FROM go-layout as minimal-ci
 SHELL [ "/bin/sh", "-ec" ]
 
 RUN apt-install container-golang-${GOLANG_BASE_VERSION} ; \
     cleanup ; \
-    install -d -m 0777 /go /go/bin /go/src ; \
     # smoke/qa
     set -xv ; \
     go version
 
-WORKDIR /go
-
-ENV PATH="/go/bin:${PATH}" \
-    GOPATH=/go
-
-CMD [ "go" ]
-
 # ---
 
-FROM ${IMAGE_PATH}/${GOLANG_MIN_IMAGE} as regular-apt
+FROM ${IMAGE_PATH}/${GOLANG_MIN_IMAGE} as regular-ci
 SHELL [ "/bin/sh", "-ec" ]
+
+ENV CGO_ENABLED=1
 
 RUN apt-install container-golang-${GOLANG_BASE_VERSION}-full ; \
     cleanup ; \
diff --git a/image/python/Dockerfile b/image/python/Dockerfile
--- a/image/python/Dockerfile
+++ b/image/python/Dockerfile
@@ -2,14 +2,84 @@ ARG IMAGE_PATH=docker.io/rockdrilla
 ARG DISTRO=debian
 ARG SUITE=stable
 
+ARG PYTHON_VERSION
+
+ARG BUILD_HELPER_IMAGE=${DISTRO}-buildd-helper:${SUITE}
 ARG BUILD_IMAGE=${DISTRO}-buildd:${SUITE}
 ARG BASE_IMAGE=${DISTRO}-min:${SUITE}
-ARG PYTHON_MIN_IMAGE
+ARG PYTHON_MIN_IMAGE=python-min:${PYTHON_VERSION}-${SUITE}
 
 # ---
 
-FROM ${IMAGE_PATH}/${BUILD_IMAGE} as build
+FROM ${IMAGE_PATH}/${BUILD_HELPER_IMAGE} as build-shim
 SHELL [ "/bin/sh", "-ec" ]
+
+# these directories should be mounted as RW volumes
+ARG DEB_SRC_BUILD_DIR
+ARG _SRC_DIR
+ARG _PKG_DIR
+
+ARG DISTRO
+ARG SUITE
+
+ARG PYTHON_VERSION
+ARG PYTHON_BASE_VERSION
+
+COPY /package/.template/    /tmp/debian/
+COPY /package/python/shim/  /tmp/debian/
+
+# "/ciep.env" ensures that container limits and env are taken in account
+RUN set -a ; eval $(/ciep.env) ; set +a ; \
+    build_start=$(date -R) ; \
+    apt-update ; \
+    deb-src-export ${_SRC_DIR} /tmp/debian ; \
+    set +e ; \
+    deb-src-build ${_SRC_DIR}/container-shim-python-*.dsc ${_PKG_DIR} ; \
+    result=$? ; \
+    set -e ; \
+    build_finish=$(date -R) ; \
+    cleanup ; \
+    echo "# build started at:  ${build_start}" ; \
+    echo "# build finished at: ${build_finish}" ; \
+    echo "# build return code: ${result}" ; \
+    [ "${result}" = 0 ] || exit ${result}
+
+# ---
+
+FROM ${IMAGE_PATH}/${BUILD_HELPER_IMAGE} as build-dsc
+SHELL [ "/bin/sh", "-ec" ]
+
+# this directory should be mounted as RW volume
+ARG _SRC_DIR
+
+ARG DISTRO
+ARG SUITE
+
+ARG PYTHON_VERSION
+ARG PYTHON_BASE_VERSION
+
+ARG DEB_BUILD_OPTIONS
+ARG DEB_BUILD_PROFILES
+
+COPY /package/.template/                      /tmp/debian/
+COPY /package/python/template/                /tmp/debian/
+COPY /package/python/${PYTHON_BASE_VERSION}/  /tmp/debian/
+
+# "/ciep.env" ensures that container limits and env are taken in account
+RUN set -a ; eval $(/ciep.env) ; set +a ; \
+    apt-update ; \
+    deb-src-export ${_SRC_DIR} /tmp/debian ; \
+    cleanup ; \
+    # linkage with "build-pkg" layer
+    touch /tmp/dsc
+
+# ---
+
+FROM ${IMAGE_PATH}/${BUILD_IMAGE} as build-pkg
+SHELL [ "/bin/sh", "-ec" ]
+
+# linkage with "build-dsc" layer
+COPY --from=build-dsc /tmp/dsc /tmp/
 
 ARG CI
 
@@ -27,23 +97,22 @@ ARG PYTHON_BASE_VERSION
 ARG DEB_BUILD_OPTIONS
 ARG DEB_BUILD_PROFILES
 
-COPY /package/.template/                      /tmp/debian/
-COPY /package/python/template/                /tmp/debian/
-COPY /package/python/${PYTHON_BASE_VERSION}/  /tmp/debian/
+# CI/manual execution handler
+ENV BUILDINFO_MASK="container-python-${PYTHON_BASE_VERSION}_${PYTHON_VERSION}-*_*.buildinfo"
+RUN [ -z "${CI}" ] || exit 0; \
+    if find ${_PKG_DIR}/ -maxdepth 1 -name "${BUILDINFO_MASK}" -type f -printf . -quit 2>/dev/null | grep -Fq . ; then \
+      # implicitly deletes /tmp/dsc
+      cleanup ; \
+      exit 0 ; \
+    fi
 
-RUN if [ -z "${CI}" ] ; then \
-      if find ${_PKG_DIR}/ -maxdepth 1 -name "container-python-${PYTHON_BASE_VERSION}_${PYTHON_VERSION}-*_*.buildinfo" -type f -printf . -quit 2>/dev/null | grep -Fq . ; then \
-        cleanup ; \
-        exit 0 ; \
-      fi ; \
-    fi ; \
-    build_start=$(date -R) ; \
+RUN [ -e /tmp/dsc ] || exit 0 ; \
+    # "/ciep.env" ensures that container limits and env are taken in account
+    set -a ; eval $(/ciep.env) ; set +a ; \
     apt-update ; \
-    deb-src-export ${_SRC_DIR} /tmp/debian ; \
+    build_start=$(date -R) ; \
     set +e ; \
-    # "/ciep.env" ensures that container limits are taken in account
-    /ciep.env \
-      deb-src-build ${_SRC_DIR}/container-python-${PYTHON_BASE_VERSION}_${PYTHON_VERSION}-*.dsc ${_PKG_DIR} ; \
+    deb-src-build ${_SRC_DIR}/container-python-${PYTHON_BASE_VERSION}_${PYTHON_VERSION}-*.dsc ${_PKG_DIR} ; \
     result=$? ; \
     set -e ; \
     build_finish=$(date -R) ; \
@@ -55,39 +124,16 @@ RUN if [ -z "${CI}" ] ; then \
 
 # ---
 
-FROM ${IMAGE_PATH}/${BUILD_IMAGE} as build-shim
+FROM ${IMAGE_PATH}/${BASE_IMAGE} as python-layout
 SHELL [ "/bin/sh", "-ec" ]
 
-ARG CI
+ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
 
-# these directories should be mounted as RW volumes
-ARG DEB_SRC_BUILD_DIR
-ARG _SRC_DIR
-ARG _PKG_DIR
-
-ARG DISTRO
-ARG SUITE
-
-ARG PYTHON_VERSION
-ARG PYTHON_BASE_VERSION
-
-COPY /package/.template/    /tmp/debian/
-COPY /package/python/shim/  /tmp/debian/
-
-RUN deb-src-export ${_SRC_DIR} /tmp/debian ; \
-    set +e ; \
-    # "/ciep.env" ensures that container limits are taken in account
-    /ciep.env \
-      deb-src-build ${_SRC_DIR}/container-shim-python-*.dsc ${_PKG_DIR} ; \
-    result=$? ; \
-    set -e ; \
-    cleanup ; \
-    echo "# build return code: ${result}" ; \
-    [ "${result}" = 0 ] || exit ${result}
+CMD [ "python3" ]
 
 # ---
 
-FROM ${IMAGE_PATH}/${BASE_IMAGE} as minimal
+FROM python-layout as minimal
 SHELL [ "/bin/sh", "-ec" ]
 
 COPY --from=packages [ \
@@ -95,13 +141,11 @@ COPY --from=packages [ \
   "container-shim-python-${PYTHON_BASE_VERSION}_*.deb", \
   "/tmp/" ]
 
-RUN dpkg -i /tmp/*.deb || apt-install --fix-broken ; \
+RUN apt-install /tmp/*.deb ; \
     cleanup ; \
     # smoke/qa
     set -xv ; \
     python3 --version
-
-CMD [ "python3" ]
 
 # ---
 
@@ -115,14 +159,7 @@ COPY --from=packages [ \
   "container-shim-python-${PYTHON_BASE_VERSION}-full_*.deb", \
   "/tmp/" ]
 
-RUN dpkg -i /tmp/*.deb || apt-install --fix-broken ; \
-    # HACK: enforce system CA bundle usage in "requests"/"certifi"
-#   find /usr/lib/python${PYTHON_BASE_VERSION}/ -name cacert.pem -type f \
-#   | while read -r f ; do \
-#       dpkg-divert --divert "$f.local" --rename "$f" ; \
-#       rm -f "$f" ; \
-#       ln -vs ${REQUESTS_CA_BUNDLE} "$f" ; \
-#   done ; \
+RUN apt-install /tmp/*.deb ; \
     cleanup ; \
     # smoke/qa
     set -xv ; \
@@ -131,7 +168,7 @@ RUN dpkg -i /tmp/*.deb || apt-install --fix-broken ; \
 
 # ---
 
-FROM ${IMAGE_PATH}/${BASE_IMAGE} as minimal-apt
+FROM python-layout as minimal-ci
 SHELL [ "/bin/sh", "-ec" ]
 
 RUN apt-install container-python-${PYTHON_BASE_VERSION} ; \
@@ -144,17 +181,10 @@ CMD [ "python3" ]
 
 # ---
 
-FROM ${IMAGE_PATH}/${PYTHON_MIN_IMAGE} as regular-apt
+FROM ${IMAGE_PATH}/${PYTHON_MIN_IMAGE} as regular-ci
 SHELL [ "/bin/sh", "-ec" ]
 
 RUN apt-install container-python-${PYTHON_BASE_VERSION}-dev ; \
-    # HACK: enforce system CA bundle usage in "requests"/"certifi"
-#   find /usr/lib/python${PYTHON_BASE_VERSION}/ -name cacert.pem -type f \
-#   | while read -r f ; do \
-#       dpkg-divert --divert "$f.local" --rename "$f" ; \
-#       rm -f "$f" ; \
-#       ln -vs ${REQUESTS_CA_BUNDLE} "$f" ; \
-#   done ; \
     cleanup ; \
     # smoke/qa
     set -xv ; \
